In [7]:
import numpy as np
from scipy.special import softmax

# Representing the encoder representations of four different words
word_1 = np.array([1, 0, 0])
word_2 = np.array([0, 1, 0])
word_3 = np.array([1, 1, 0])
word_4 = np.array([0, 0, 1])

# word embeddings.
words = np.array([word_1, word_2, word_3, word_4])

# Generating the weight matrices.
np. random.seed(42)
W_Q = np. random.randint(3, size=(3, 3))
W_K = np. random.randint(3, size=(3, 3))
W_V = np. random.randint(3, size=(3, 3))

# Generating the queries, keys, and values.
Q = np.dot(words, W_Q)
K = np.dot(words, W_K)
V = np.dot(words, W_V)

# Scoring vector query.
scores = np.dot(Q, K.T)

# Computing the weights by applying a softmax operation.
weights = softmax(scores / np.sqrt(K.shape[1]), axis=1)

# Computing the attention by calculating the weighted sum of the value vectors.
attention = np.dot(weights, V)

print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]


In [1]:
import numpy as np
from scipy.special import softmax

# encoder representations of four different words
word_1 = np.array([1, 0, 0])
word_2 = np.array([0, 1, 0])
word_3 = np.array([1, 1, 0])
word_4 = np.array([0, 0, 1])

In [2]:
np.random.seed(42) 
W_Q = np.random.randint(3, size=(3, 3))
W_K = np.random.randint(3, size=(3, 3))
W_V = np.random.randint(3, size=(3, 3))

In [3]:
query_1 = np.dot(word_1, W_Q)
key_1 = np.dot(word_1, W_K)
value_1 = np.dot(word_1, W_V)

query_2 = np.dot(word_2, W_Q)
key_2 = np.dot(word_2, W_K)
value_2 = np.dot(word_2, W_V)

query_3 = np.dot(word_3, W_Q)
key_3 = np.dot(word_3, W_K)
value_3 = np.dot(word_3, W_V)

query_4 = np.dot(word_4, W_Q)
key_4 = np.dot(word_4, W_K)
value_4 = np.dot(word_4, W_V)

In [15]:
scores1 = np.array([np.dot(query_1,key_1),np.dot(query_1,key_2),np.dot(query_1,key_3),np.dot(query_1,key_4)])

weights1 = softmax(scores1 / np.sqrt(key_1.shape[0]))

attention1=(weights1[0]*value_1)+(weights1[1]*value_2)+(weights1[2]*value_3)+(weights1[3]*value_4)
print(attention1)

[0.98522025 1.74174051 0.75652026]


In [9]:
scores2 = np.array([np.dot(query_2,key_1),np.dot(query_2,key_2),np.dot(query_2,key_3),np.dot(query_2,key_4)])
weights2 = softmax(scores2 / np.sqrt(key_2.shape[0]))
attention2=(weights2[0]*value_1)+(weights2[1]*value_2)+(weights2[2]*value_3)+(weights2[3]*value_4)
print(attention2)

[0.90965265 1.40965265 0.5       ]


In [11]:
scores3 = np.array([np.dot(query_3,key_1),np.dot(query_3,key_2),np.dot(query_3,key_3),np.dot(query_3,key_4)])
weights3 = softmax(scores3 / np.sqrt(key_3.shape[0]))
attention3=(weights3[0]*value_1)+(weights3[1]*value_2)+(weights3[2]*value_3)+(weights3[3]*value_4)
print(attention3)

[0.99851226 1.75849334 0.75998108]


In [12]:
scores4 = np.array([np.dot(query_4,key_1),np.dot(query_4,key_2),np.dot(query_4,key_3),np.dot(query_4,key_4)])
weights4 = softmax(scores4 / np.sqrt(key_4.shape[0]))
attention4=(weights4[0]*value_1)+(weights4[1]*value_2)+(weights4[2]*value_3)+(weights4[3]*value_4)
print(attention4)

[0.99560386 1.90407309 0.90846923]
