In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

# Using pre-trained model

In [2]:
cd Downloads

C:\Users\acer\Downloads


In [3]:
#Download below pretrained file from this link 
#"https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit"
model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin.gz',binary=True)

In [4]:
model['bottle'].sha̱pe

AttributeError: 'numpy.ndarray' object has no attribute 'sha̱pe'

In [5]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [6]:
model.most_similar('man')

[('woman', 0.7664011716842651),
 ('boy', 0.6824870109558105),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [7]:
model.similarity('man','woman')

0.76640123

# Training from scratch

In [8]:
import os
from nltk import sent_tokenize
import nltk
nltk.download('punkt')
from gensim.utils import simple_preprocess
#Download below dataset from this link "https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books/data"
story = []
for filename in os.listdir('data'):
    f = open(os.path.join('data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [9]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [11]:
# Training the Word2Vec model
#w2v_model = gensim.models.Word2Vec(story,window=10,min_count=2)
#w2v_model=gensim.models.Word2Vec(window=10,min_count=2)
model = Word2Vec(story, window=10,min_count=2)

In [12]:
model.wv['jon']

array([-0.22991593, -1.8013031 ,  0.01901897, -1.0185316 ,  1.3424855 ,
        2.0987306 ,  0.09491033, -1.7839413 ,  0.28721285, -0.27351812,
       -0.64406675,  0.27579126,  0.40915453, -1.7986137 ,  0.22671734,
       -0.02385887,  1.3227609 ,  3.7267418 ,  0.8669054 , -0.8835834 ,
        1.8466074 , -2.8087301 , -0.50439674,  0.7880911 , -0.46827474,
       -1.737977  ,  1.1817516 ,  0.18793352,  1.4777942 , -1.3713194 ,
       -1.0030032 , -0.7748517 ,  1.4406967 , -0.91340905, -0.3529698 ,
        1.3379536 ,  2.1230404 ,  0.21819137,  0.98797965, -1.9450669 ,
        0.3411827 , -1.662958  ,  0.9280742 ,  2.1328046 ,  1.6349698 ,
       -2.8771374 ,  0.16979146,  1.6169121 , -1.1526774 , -0.3734517 ,
       -0.84380853, -1.5227001 ,  1.6578292 ,  0.83879465, -0.12381484,
        0.7313191 ,  0.19601662, -0.7746843 ,  0.0900775 ,  1.0300144 ,
        0.83918494,  2.4374444 ,  1.1735253 , -1.5109305 , -0.28088722,
        0.6747967 ,  0.5919665 ,  3.1262748 , -0.82199275,  0.35

In [13]:
model.wv['jon'].shape

(100,)

In [27]:
# Getting vocabulary of wards.
#model.wv.vocab
model.wv.index_to_key

17453

In [16]:
model.build_vocab(story)

In [17]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6570182, 8628190)

In [31]:
model.save("./word2vec-amazon-cell-accessories-reviews-short.model")

In [18]:
# Most similar words
model.wv.most_similar('daenerys')

[('stormborn', 0.6980600953102112),
 ('unburnt', 0.6270902156829834),
 ('elia', 0.6220109462738037),
 ('targaryen', 0.5997449159622192),
 ('westeros', 0.5462070107460022),
 ('viserys', 0.545362651348114),
 ('queen', 0.5410561561584473),
 ('drogo', 0.5127058625221252),
 ('wed', 0.5121884346008301),
 ('margaery', 0.5118104219436646)]

In [19]:
model.wv.doesnt_match(['cersei', 'jaime', 'bronn', 'tyrion' ])

'bronn'

In [20]:
model.wv.similarity('arya','sansa')

0.8146642

In [21]:
model.wv.similarity('tyin','sansa')

KeyError: "Key 'tyin' not present"

In [22]:
model.wv.get_normed_vectors()

array([[-0.02722444,  0.10783425,  0.01103699, ..., -0.06878426,
         0.17938328, -0.01372673],
       [ 0.02868557,  0.00107516,  0.23135068, ..., -0.18596599,
        -0.0310153 , -0.02045854],
       [-0.00499146, -0.18531346,  0.04450803, ..., -0.03795866,
         0.11115279,  0.10616386],
       ...,
       [-0.02389492,  0.12693289,  0.01189446, ..., -0.13057706,
        -0.01735302, -0.06400477],
       [-0.05813754,  0.10305735,  0.00999465, ..., -0.06670492,
         0.05157274, -0.12844874],
       [-0.04912634,  0.03090745,  0.10733669, ..., -0.08011453,
         0.04356935, -0.13630976]], dtype=float32)

In [29]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)

X = pca.fit_transform(model.wv.get_normed_vectors())

X. shape



import plotly.express as px
fig = px.scatter_3d(X[:500],x=0,y=1,z=2,color=model.wv.index_to_key[:500])
fig.show()

In [24]:
# average Word2Vec
# compute average word2vec for each review.
sent_vectors = []; # the avg-w2v for each sentence/review is stored in this
for sent in list_of_sent: # for each review/sentence
    sent_vec = np.zeros(50) # as word vectors are of zero length
    cnt_words =0; # num of words with a valid vector in the sentence/review
    for word in sent: # for each word in a review/sentence
        try:
            vec = model.wv[word]
            sent_vec += vec
            cnt_words += 1
        except:
            pass
    sent_vec /= cnt_words
    sent_vectors.append(sent_vec)
print(len(sent_vectors))
print(len(sent_vectors[0]) )

NameError: name 'list_of_sent' is not defined

In [ ]:
# TF-IDF weighted Word2Vec
tfidf_feat = tf_idf_vect.get_feature_names() # tfidf words/col-names
# final_tf idf is the sparse matrix with row= sentence, col=word and cell v

tfidf_sent_vectors = []; # the tfidf-w2v for each sentence/review is stored
row=0;
for sent in list_of_sent: # for each review/sentence
    sent_vec = np.zeros(50) # as word vectors are of zero length
    weight_sum =0; # num of words with a valid vector in the sentence/revie
    for word in sent: # for each word in a review/sentence
        try:
            vec = model.wv[word]
            # obtain the tf_idfidf of a word in a sentence/review
            tfidf = final_tf_idf[row, tfidf_feat.index(word)]
            sent_vec += (vec * tf_idf)
            weight_sum += tf_idf
        except :
            pass
    sent vec /= weight sum